// Generated by gencpp from file jalan_dong/image_msgs.msg
// DO NOT EDIT!


#ifndef JALAN_DONG_MESSAGE_IMAGE_MSGS_H
#define JALAN_DONG_MESSAGE_IMAGE_MSGS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jalan_dong
{
template <class ContainerAllocator>
struct image_msgs_
{
  typedef image_msgs_<ContainerAllocator> Type;

  image_msgs_()
    : x(0)
    , y(0)  {
    }
  image_msgs_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef int16_t _x_type;
  _x_type x;

   typedef int16_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::jalan_dong::image_msgs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jalan_dong::image_msgs_<ContainerAllocator> const> ConstPtr;

}; // struct image_msgs_

typedef ::jalan_dong::image_msgs_<std::allocator<void> > image_msgs;

typedef boost::shared_ptr< ::jalan_dong::image_msgs > image_msgsPtr;
typedef boost::shared_ptr< ::jalan_dong::image_msgs const> image_msgsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jalan_dong::image_msgs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jalan_dong::image_msgs_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace jalan_dong

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'jalan_dong': ['/home/mfikih15/Documents/mekatron/src/jalan_dong/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::jalan_dong::image_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jalan_dong::image_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jalan_dong::image_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jalan_dong::image_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jalan_dong::image_msgs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jalan_dong::image_msgs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jalan_dong::image_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d78a6b8c9650c754bf0432d3d1707c3";
  }

  static const char* value(const ::jalan_dong::image_msgs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d78a6b8c9650c75ULL;
  static const uint64_t static_value2 = 0x4bf0432d3d1707c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::jalan_dong::image_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jalan_dong/image_msgs";
  }

  static const char* value(const ::jalan_dong::image_msgs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jalan_dong::image_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 x\n\
int16 y\n\
";
  }

  static const char* value(const ::jalan_dong::image_msgs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jalan_dong::image_msgs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct image_msgs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jalan_dong::image_msgs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jalan_dong::image_msgs_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JALAN_DONG_MESSAGE_IMAGE_MSGS_H
